### ISSUE TITLE
Origen segregació

### ISSUE THREAD

**Issue by COETTC** [COETTC/Estatuts#2]
Definir origen segregació

**Comment by pedro-nonfree** [comment]
Està treballat en commit https://github.com/COETTC/Estatuts/pull/1/commits/dfc943cfaba8706858cad857c9a95fe4738ba40f, que és un commit a #1 però primer s'ha d'aprovar/merge aquest PR abans de donar aquesta issue per tancada

**Comment by pedro-nonfree** [comment]
resolt en https://github.com/COETTC/Estatuts/pull/1
